# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainFunctions.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class mainFunctions(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1109, 600)
        Dialog.setMinimumSize(1109,600)
        Dialog.setMaximumSize(1109,600)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.setStyleSheet("Background-Color: #363636; ")
        self.frameBigUtilities = QtWidgets.QFrame(self.frame)
        self.frameBigUtilities.setGeometry(QtCore.QRect(480, 10, 422, 515))
        self.frameBigUtilities.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBigUtilities.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBigUtilities.setObjectName("frameBigUtilities")
        self.frameBtns = QtWidgets.QFrame(self.frameBigUtilities)
        self.frameBtns.setGeometry(QtCore.QRect(20, 250, 550, 60))
        self.frameBtns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBtns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBtns.setObjectName("frameBtns")
        self.frameBtns.setStyleSheet("Background-color: #423C3C;")
        self.radioBtnDetect = QtWidgets.QRadioButton(self.frameBtns)
        self.radioBtnDetect.setGeometry(QtCore.QRect(139, 0, 102, 30))
        self.radioBtnDetect.setObjectName("radioBtnDetect")
        self.radioBtnDetect.setStyleSheet("Color: White; border-style: outset; border-width: 1px; border-color: White;")
        self.frameUseMode = QtWidgets.QFrame(self.frameBtns)
        self.frameUseMode.setGeometry(QtCore.QRect(65, 0, 75, 91))
        self.frameUseMode.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameUseMode.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameUseMode.setObjectName("frameUseMode")
        self.frameUseMode.setStyleSheet("Color: White; ")
        self.label = QtWidgets.QLabel(self.frameUseMode)
        self.label.setGeometry(QtCore.QRect(0, 0, 75, 30))
        self.label.setObjectName("label")
        self.label.setStyleSheet("border-style: outset; border-width: 1px; border-color: White;")
        self.radioBtnSearch = QtWidgets.QRadioButton(self.frameBtns)
        self.radioBtnSearch.setGeometry(QtCore.QRect(239, 0, 102, 30))
        self.radioBtnSearch.setObjectName("radioBtnSearch")
        self.radioBtnSearch.setStyleSheet("Color: White; border-style: outset; border-width: 1px; border-color: White;")
        self.groupBox = QtWidgets.QGroupBox(self.frameBtns)
        self.groupBox.setGeometry(QtCore.QRect(0, 29, 401, 31))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 10, 90, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton.setStyleSheet("Color: White;outset; border-width: 1px; border-color: White;" )
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(160, 10, 90, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_2.setStyleSheet("Color: White;outset; border-width: 1px; border-color: White;")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(310, 10, 90, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_3.setStyleSheet("Color: White;outset; border-width: 1px; border-color: White;")
        self.radioButton_3.raise_()
        self.radioButton_2.raise_()
        self.radioButton.raise_()
        self.btnConfirm = QtWidgets.QPushButton(self.frameBigUtilities)
        self.btnConfirm.setGeometry(QtCore.QRect(75, 320, 93, 28))
        self.btnConfirm.setObjectName("btnConfirm")
        self.btnConfirm.setStyleSheet("Background-color: #4D4845;" "Color:White;")
        self.btnCancel = QtWidgets.QPushButton(self.frameBigUtilities)
        self.btnCancel.setGeometry(QtCore.QRect(250, 320, 93, 28))
        self.btnCancel.setObjectName("btnCancel")
        self.btnCancel.setStyleSheet("Background-color: #4D4845;" "Color:White;")
        self.video = QtWidgets.QLabel(self.frame)
        self.video.setGeometry(QtCore.QRect(0, 0, 481, 531))
        self.video.setText("")
        self.video.setObjectName("video")
        self.horizontalLayout.addWidget(self.frame)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.radioBtnDetect.setText(_translate("Dialog", "Detectar rostros"))
        self.label.setText(_translate("Dialog", "Modo de uso:"))
        self.radioBtnSearch.setText(_translate("Dialog", "Buscar rostro"))
        self.radioButton.setText(_translate("Dialog", "Algoritmo 1"))
        self.radioButton_2.setText(_translate("Dialog", "Algoritmo 2"))
        self.radioButton_3.setText(_translate("Dialog", "Algoritmo 3"))
        self.btnConfirm.setText(_translate("Dialog", "Iniciar"))
        self.btnCancel.setText(_translate("Dialog", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = mainFunctions()
    #ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
